language: python
python:
  - "2.7"
# Install non-pip dependencies
addons:
  apt:
    packages:
      - librrd-dev
# Install dependencies
install:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - pip install coveralls
    - pip install pyflakes==1.2.3
    - pip install pylint==1.5.6
    - pip install yapf==0.10.0
script:
    # See fake-packages/README.md for background on why we need fake-packages.
    - PYTHONPATH=$PYTHONPATH:$PWD/fake-packages ./build
after_success:
    - coveralls
sudo: false
