language: python
python:
  - "2.7"
# Install non-pip dependencies
addons:
  apt:
    packages:
      - librrd-dev
# Install dependencies
install:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - pip install coveralls
    - pip install pyflakes==1.0.0
    - pip install yapf==0.7.0
    - pip install pylint==1.5.5
script:
    # Run unit tests
    - python -m unittest discover -s export/ -p '*_test.py'
    - python -m unittest discover -s monitoring/ -p '*_test.py'
    - python -m unittest discover -s plugin/ -p '*_test.py'
    - python -m unittest discover -s system/vsys/ -p '*_test.py'
    - python -m unittest discover -s site-packages/ -p '*_test.py'
    # Run auto formatter.
    - yapf --diff --recursive --style google ./ --exclude=./third_party/*
    # Run static analysis for Python bugs/cruft.
    - pyflakes ./
    # Run the docstring lint checker.
    - PYTHONPATH=$PYTHONPATH:$PWD/third_party/docstringchecker pylint --reports=n plugin/*.py export/*.py monitoring/*.py system/vsys/*.py site-packages/mlab/disco/*.py
sudo: false
