language: python
python:
  - "2.7"
# Install non-pip dependencies
addons:
  apt:
    packages:
      - librrd-dev
# Install dependencies
install:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
# Run unit tests
script:
    - python -m unittest discover -s export/ -p '*_test.py'
    - python -m unittest discover -s monitoring/ -p '*_test.py'
    - python -m unittest discover -s plugin/ -p '*_test.py'
    - python -m unittest discover -s system/vsys/ -p '*_test.py'
sudo: false
