language: python
python:
  - "2.7"
# Install non-pip dependencies
addons:
  apt:
    packages:
      - librrd-dev
# Install dependencies
install:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - pip install yapf==0.7.0
script:
    # YAPF must be first or it causes Travis to hang for some reason.
    - yapf --diff --recursive --style google ./
    # Run unit tests
    - python -m unittest discover -s export/ -p '*_test.py'
    - python -m unittest discover -s monitoring/ -p '*_test.py'
    - python -m unittest discover -s plugin/ -p '*_test.py'
    - python -m unittest discover -s system/vsys/ -p '*_test.py'
sudo: false
